name: Test and Format

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  format-and-test:
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Display Python version
        run: python --version

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install formatting packages
        run: pip install black autopep8 isort

      - name: Format code
        run: |
          black .
          autopep8 --recursive --in-place --aggressive --aggressive .
          isort .

      - name: Commit formatted code
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git diff --staged --quiet || git commit -m "Automatically format Python code and run tests"
          git push origin ${GITHUB_REF_NAME}
